### ISSUE TITLE
Request to support Markdown Notes and Hide Mnemonic scripts

### ISSUE THREAD

**Issue by mondaiguy** [cplaverty/KeitaiWaniKani#1]
Hi Chris,

Love your app - it's my favorite of the ones I've tried. I guess there's only two now for iOS, but there used to be three.

There are two scripts that I really hope you consider adding, if it's possible. The first is:

**WaniKani Markdown Notes**
https://greasyfork.org/en/scripts/15778-wanikani-markdown-notes

I like to make my own mnemonics for radicals, kanji, and vocabulary. Sometimes I write an entirely new one, or sometimes I just re-word the default one. But re-writing or coming up with my own really helps make it stick into my mind better. Of course, when you make your own mnemonics via the notes, by default WaniKani doesn't let you use the helpful colors for radicals (blue), kanji (pink), vocabulary meaning (purple), vocabulary reading (white text on a black background). This script makes that possible. It also enables users to use **bold** and _italic_ formatting, and add [links](http://www.wanikani.com/) and even images. (I think images are a bit overkill, but everything else is helpful.) I don't see myself adding markdown from an iOS app, but I would like to see my markdown that I did on the desktop rendered in the iOS app, and currently no app supports the script, so all my markdown just shows up as unrendered text, which makes it difficult to read. (So I can't really use the app to study, but just do reviews.)

The other script I wanted to suggest adding support for is:

**WaniKani hide mnemonics**
https://greasyfork.org/en/scripts/7577-wanikani-hide-mnemonics

This one lets you hide the default mnemonics so you can focus on the ones you've written. Without the script, everything shows, and it's just a lot more information coming at you, and a lot more messy looking.

You can envision what this page might look like in the iOS apps without these two scripts:

https://dl.dropboxusercontent.com/u/1697331/2016-02-12_with.png

In this screenshot, I turned on both scripts, so you see that I've hidden the two default mnemonics, and you can see my own custom mnemonic (I usually just do one for "reading" and include the meaning the same one, to help "tie things together"), which is showing with the proper custom colors (via the first script).

Here's another screenshot, which shows the same page without either script activated. You can see the default mnemonics now, and my custom colors are just a bunch of messy markup. You can imagine what this page would look like in your app, which has even less screen real estate since it's being viewed on a smaller device:

https://dl.dropboxusercontent.com/u/1697331/2016-02-12_without.png

It's just much longer and there's so much more information to process. I like keeping things simple.

Thank you for your consideration!

**Comment by cplaverty** [comment]
Hi there!

Thanks for the suggestion.  I've had a look at the scripts, and I think getting them integrated should be fairly straightforward.  It might be a few weeks before I've the opportunity to do so, but I'll aim to get them in for the next version (2.1).

**Comment by mondaiguy** [comment]
Oh man, thank you so, so much. This will help me so much.

**Comment by cplaverty** [comment]
Released beta version of 2.0.1 which adds support for these user scripts.

**Comment by mondaiguy** [comment]
Very cool. Maybe a dumb question: can I get the beta through TestFlight if invited or only through GitHub, or?

**Comment by cplaverty** [comment]
Mail me your email address to allicrab@icloud.com and I'll add you to the TestFlight list.
