### ISSUE TITLE
"Current Level Time" incorrect after reset

### ISSUE THREAD

**Issue by almercier** [cplaverty/KeitaiWaniKani#22]
Resetting my level back to level 2 now displays the "current level time" from the date/time I _originally_ got to the level and not when I had gotten to the level again. This may be on WK API's side for all I know...

![image](https://user-images.githubusercontent.com/30079507/51629264-22323200-1f15-11e9-85c9-f74b63d943dd.png)

Side note: I'm really looking forward to the v3 release! #15 is pretty annoying sometimes.

**Comment by almercier** [comment]
Looking further, I see you are calculating the "current level time" based on earliest point at which an item was unlcoked in the level because the WaniKani API does not supply an actual level start time.

There may not be a way to determine level start time post-reset with the info received from the API...

**Comment by cplaverty** [comment]
Yeah the correct solution here is to actually use the level_progression data that AlliCrab is currently fetching but ignoring.
https://docs.api.wanikani.com/20170710/#level-progressions

This doesn't contain the complete level history for those who have been on the site for a few years (like me), so in this case the app needs to merge the guessed history with the actual history.  It's been on my list for years and I intend to fix this before it goes live.

**Comment by cplaverty** [comment]
Fixed in beta 79
