### ISSUE TITLE
Keyboard goes away after each answer

### ISSUE THREAD

**Issue by BaelfireNightshd** [cplaverty/KeitaiWaniKani#24]
TestFlight Version 3.0(83)
iOS version: 12.2
iPhone 7+

Keyboard disappears and you have to tap on the input field after each answer. 

Looks like you fixed a similar issue for iOS 11.3 about 10 months ago. 

But in the latest beta, the fix doesn’t appear to work.

**Comment by cplaverty** [comment]
This has been fixed in the beta version 3.0 b84

**Comment by BaelfireNightshd** [comment]
Can confirm. Works beautifully. Thank you!
