### ISSUE TITLE
Review timeline filter/display options do not stick?

### ISSUE THREAD

**Issue by almercier** [cplaverty/KeitaiWaniKani#26]
This may be as designed, but the UI/UX makes it seem like these are settings that are meant to stick when leaving and coming back to the review timeline. Maybe it would be cleaner to have it stick until the app is closed rather than until the review timeline is closed?

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/30079507/59105779-b3bda180-8902-11e9-9a80-de8102a6b4bb.gif)

**Comment by cplaverty** [comment]
Fair point. I should persist these settings.
