### ISSUE TITLE
Feature Request: Script descriptions

### ISSUE THREAD

**Issue by almercier** [cplaverty/KeitaiWaniKani#28]
I'd like to request a short (1-2 sentences) description below each user script so that users know what the script does. It's not exactly obvious with the names sometimes, and it's a pain to click the forum topic and pull up a browser instance to see what it does.

"Disable Lesson Swipe" doesn't even have a forum topic, and I'm not 100% what it does.

![IMG_4579](https://user-images.githubusercontent.com/30079507/59107284-46137480-8906-11e9-90a4-b62ee2a72995.jpg)

**Comment by cplaverty** [comment]
Ah I meant to re-add the script descriptions but missed this. This used to be in v2 but didn’t add it into the new view for v3.
