### ISSUE TITLE
Bluetooth keyboard on iPad missing functionality

### ISSUE THREAD

**Issue by sleepyspider1** [cplaverty/KeitaiWaniKani#3]
When using a bluetooth keyboard with the ipad, many of the hotkeys do not work like "f" and "spacebar".

When you get an item wrong, you can't just press the "enter" key, you have to manually tap the screen. Seems to be a focusing issue. Pressing "tab" or "shift+tab" does nothing to regain focus.

**Comment by cplaverty** [comment]
The proper fix for this is to move back to WKWebView for the review page web view.  My plan was to have a look at the iOS 10 beta that I expect to be released over WWDC next week and see if keyboard focus for WKWebView behaves as expected.

**Comment by cplaverty** [comment]
Finally fixed in 2.2, just released to the App Store.
