### ISSUE TITLE
Bug: incorrect lessons and reviews after IOS update 

### ISSUE THREAD

**Issue by trentkg** [cplaverty/KeitaiWaniKani#32]
After downloading the latest IOS update I’ve noticed that the lessons and reviews are now inaccurate. It says I have 53 lessons available (I’ve had 0 for some time) and I have 8 reviews Available (I have none). When I get new reviews, the number increments and when I complete them it decrements, but it never goes below 8.

**Comment by cplaverty** [comment]
Can you email me a WaniKani v2 API key so I can look into this? allicrab@icloud.com

**Comment by trentkg** [comment]
Sure - where do I get that? At the bottom of the app I see I’m running AlliCrab v 3.0, build 87

**Comment by cplaverty** [comment]
Easiest place to get it is from the WaniKani settings page:
https://www.wanikani.com/settings/personal_access_tokens

**Comment by trentkg** [comment]
Sent

**Comment by cplaverty** [comment]
Thanks for sending me your API key.  I have had a look and can see what the issue is, so I'll get that fixed.

**Comment by cplaverty** [comment]
Beta version with this fix has been released if you're not already signed up for betas through TestFlight: https://testflight.apple.com/join/K7OOa3bb
