### ISSUE TITLE
Long vocabulary splits into multiple lines

### ISSUE THREAD

**Issue by chrisjwelly** [cplaverty/KeitaiWaniKani#35]
### Problem
If the vocabulary is sufficiently long (seems to be roughly more than 4 characters), the vocabulary continues into the next line. This may cause the UI to feel slightly more cluttered. 
### Screenshot
![](https://imgur.com/GckVcYf.jpg)
### Suggestion
Perhaps a smaller font for the characters can be used when such long vocabulary appears in the review queue? 
### Versions
AlliCrab version 3.0
iOS 12.3.1
On an iPhone XR
### Active Scripts
Jitai
Wanikani Improve
Wanikani Override
Disable Lesson Swipe

---
I'm not sure whether this is caused by the use of the app or simply because I'm doing reviews on mobile. I understand that only a minority of the vocabulary would cause this to happen, but I thought it would be a nice minor enhancement to make the UI neater if such a vocabulary appears.

**Comment by Mercieral** [comment]
The text font size normally adjusts to fit the screen in one line. However it looks like you have the Jitai script enabled, so I'm wondering if there is an issue there...

**Comment by almercier** [comment]
@cplaverty I'll take a look at this since it's html/JS related.

**Comment by Mercieral** [comment]
@cplaverty I can take a look at this since it is html/JS related.

**Comment by chrisjwelly** [comment]
@Mercieral Yes, my Jitai is enabled. I have updated my original post to include my current active scripts. Thanks for mentioning it; I overlooked including it in my post!

**Comment by almercier** [comment]
I stand corrected, it does this even with Jitai disabled. The review page on safari on both web and iphone zooms out if the text doesn't fit, whereas it remains the same default zoom on the webview in the app.

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/30079507/59631498-ff97f400-9115-11e9-85ce-6e7472d3642c.gif)

**Comment by cplaverty** [comment]
The font size for vocabulary on the WK site isn't dynamic; it's always that small.  Smaller than the corresponding font size for radicals and kanji.  The resize.css style sheet that is injected increases font size, but doesn't treat vocabulary differently like WK does.  Perhaps it should.

**Comment by Mercieral** [comment]
@cplaverty So from what I can tell, all WK is doing is hardcoding a font size of `6.125em` for the question, and change it to `3.0625em` in a media query when the screen is less than `767px`. I'm not seeing any logic regarding handling radical/kanji and vocab differently. The `resize.css` style sheet is overriding the font size to `10vh` bound to the height of the viewport, plus some hardcoded sizes for ipads... 

The easy solution would be to just turn down the font-size to height ratio for vocab, but there are some ways to dynamically shrink the font-size to fit only when needed which would allow for short vocab to still appear big like the radicals/kanji.
