### ISSUE TITLE
Text glitch

### ISSUE THREAD

**Issue by squintr** [cplaverty/KeitaiWaniKani#5]
Saw a text glitch in the app on the kanji page for 申... not sure if it's on WaniKani's side or yours..

https://dl.dropboxusercontent.com/u/1697331/IMG_0792.PNG

**Comment by cplaverty** [comment]
It's on their side, as I saw it frequently when I used Mobile Safari directly. It's likely I can inject a script to tidy this up though, so I'll leave this open.

**Comment by mondaiguy** [comment]
Ah ok, I'll let them know.

**Comment by cplaverty** [comment]
This issue has been open for ages, but it looks like WK fixed this at some point so I'm closing it.
