### ISSUE TITLE
Keyboard issues in Lessons mode

### ISSUE THREAD

**Issue by mondaiguy** [cplaverty/KeitaiWaniKani#6]
I've noticed that if you try to update Reading/Meaning notes in AlliCrab, at least, when you're doing new lessons, the keyboard often doesn't go away. I get stuck with it for the rest of the session and it obstructs the view for the whole time. If you get to the Quiz, you can't see the two options at the end (forgot what they are exactly, I just know one keeps you studying and the other starts the quiz). If you know to press the blue button on the keyboard ("Go", is it? - I can't remember), the quiz will start. Otherwise it'll look like you can't start the quiz.

Not sure if this happens outside of Lessons too. I think it probably does.

Is this something you are able to fix?  (By the way, I'm on the iOS 10 beta if that makes any difference.)

**Comment by iMaddin** [comment]
Is it possible that there is now a good workaround? Just installed the latest TestFlight build and while the keyboard is still stuck on screen, I can now scroll down much further so that the keyboard doesn't obstruct the meanings/readings sections anymore. 

I'm pretty sure I wasn't able to scroll down before with the keyboard being stuck on screen.

**Comment by cplaverty** [comment]
Haven't yet had a chance to look into this, but I think there's a good chance I can work around the issue. 

And yes, the new version no longer disables scrolling when the keyboard is displayed. Disabling scrolling didn't have the effect I was going for and just caused other problems (like this issue), so I removed it.

**Comment by iMaddin** [comment]
In case someone still suffers from this: when the keyboard is stuck on screen, go to the "Radicals" or "Examples" section and tap one of them, this will open a web view to the radical or example and hide the keyboard. Just navigate backwards and you'll be back without the keyboard obstructing your view.

**Comment by cplaverty** [comment]
In 2.2, I no longer remove the keyboard accessory, so the Done button is on the keyboard to allow it to be dismissed at any time.  I've removed the hacky workarounds I added that didn't really fix the problem.
