### ISSUE TITLE
Estimation on leveling up is not right anymore

### ISSUE THREAD

**Issue by agarny** [cplaverty/KeitaiWaniKani#7]
The WK guys have modified their SRS. FWIW, I started a topic on this issue on the WK forum (see [here](https://www.wanikani.com/chat/wanikani/15733)).

The bottom line is that, as done by @rfindley in his  [WaniKani API Key Haiku page](https://www.idigtech.com/wanikani/#progress), we now have: **2h**, **4h**, **8h**, **23h** (guru), **167h**, **335h** (master), **719h** (enlighten) and **2879h** (burned) up to **level 2** and **4h**, **8h**, **23h**, **47h** (guru), **167h**, **335h** (master), **719h** (enlighten) and **2879h** (burned) for the **remaining levels**. However, there are some 'short' levels (**levels 46-47** and **49-60**) which are now down to **3d10h** (from **4d10h**) while 'normal' levels last **6d20h**.

**Comment by cplaverty** [comment]
Thanks for letting me know.  Will change!

**Comment by cplaverty** [comment]
Fixed in 2.2
