### ISSUE TITLE
Reviews, Kanji, Radical, Vocab data not loading

### ISSUE THREAD

**Issue by DipeshSomvanshi** [cplaverty/KeitaiWaniKani#8]
![img_1730](https://cloud.githubusercontent.com/assets/16100480/25961613/b6f4c144-362f-11e7-8ab7-cd1aced6257e.PNG)

**Comment by cplaverty** [comment]
Hi!  I've mailed you but haven't had a reply from you.  Are you still having this issue?

**Comment by viphan** [comment]
I'm also having the same problem. It happened today.

**Comment by cplaverty** [comment]
Latest version 3 release completely replaces all this code and relies on the WaniKani API for incremental updates. That resolves this particular edge condition, so this error is now no longer possible.
